name: Build & Deploy

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."zot.home.arpa"]
              http = true
              insecure = true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: frontend
          platforms: linux/arm64
          push: true
          tags: |
            zot.home.arpa/tts-frontend:${{ github.sha }}
            zot.home.arpa/tts-frontend:prd
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: backend
          platforms: linux/arm64
          push: true
          tags: |
            zot.home.arpa/tts-backend:${{ github.sha }}
            zot.home.arpa/tts-backend:prd
          cache-from: type=gha
          cache-to: type=gha,mode=min
          
      - name: Deploy
        run: |
            kubectl apply -f backend/k8s.yaml
            kubectl apply -f frontend/k8s.yaml